test_that("give_coordinates() works as expected.", {
  expect_identical(give_coordinates("east", "forward"), list(direc = "forward", y_subject = 0, x_subject = 1))
  expect_identical(give_coordinates("east", "backward"), list(direc = "backward", y_subject = 0, x_subject = -1))
  expect_identical(give_coordinates("east", "forward", x = 8, y = 5), list(direc = "forward", y_subject = 5, x_subject = 9))
  expect_identical(give_coordinates("east", "forward", 4, 9), list(direc = "forward", y_subject = 4, x_subject = 10))
  expect_identical(give_coordinates("west", "forward"), list(direc = "forward", y_subject = 0, x_subject = -1))
  expect_identical(give_coordinates("west", "backward"), list(direc = "backward", y_subject = 0, x_subject = 1))
  expect_identical(give_coordinates("west", "forward", x = 8, y = 5), list(direc = "forward", y_subject = 5, x_subject = 7))
  expect_identical(give_coordinates("west", "forward", 4, 9), list(direc = "forward", y_subject = 4, x_subject = 8))
  expect_identical(give_coordinates("north", "forward"), list(direc = "forward", y_subject = -1, x_subject = 0))
  expect_identical(give_coordinates("north", "backward"), list(direc = "backward", y_subject = 1, x_subject = 0))
  expect_identical(give_coordinates("north", "forward", x = 8, y = 5), list(direc = "forward", y_subject = 4, x_subject = 8))
  expect_identical(give_coordinates("north", "forward", 4, 9), list(direc = "forward", y_subject = 3, x_subject = 9))
  expect_identical(give_coordinates("south", "forward"), list(direc = "forward", y_subject = 1, x_subject = 0))
  expect_identical(give_coordinates("south", "backward"), list(direc = "backward", y_subject = -1, x_subject = 0))
  expect_identical(give_coordinates("south", "forward", x = 8, y = 5), list(direc = "forward", y_subject = 6, x_subject = 8))
  expect_identical(give_coordinates("south", "forward", 4, 9), list(direc = "forward", y_subject = 5, x_subject = 9))
})
