test_that("give_coordinates() works as expected.", {
  expect_identical(give_coordinates(1i, "forward"), list(direc = "forward", I_subject = 0, J_subject = 1))
  expect_identical(give_coordinates(1i, "backward"), list(direc = "backward", I_subject = 0, J_subject = -1))
  expect_identical(give_coordinates(1i, "forward", J = 8, I = 5), list(direc = "forward", I_subject = 5, J_subject = 9))
  expect_identical(give_coordinates(1i, "forward", 4, 9), list(direc = "forward", I_subject = 4, J_subject = 10))
  expect_identical(give_coordinates(-1i, "forward"), list(direc = "forward", I_subject = 0, J_subject = -1))
  expect_identical(give_coordinates(-1i, "backward"), list(direc = "backward", I_subject = 0, J_subject = 1))
  expect_identical(give_coordinates(-1i, "forward", J = 8, I = 5), list(direc = "forward", I_subject = 5, J_subject = 7))
  expect_identical(give_coordinates(-1i, "forward", 4, 9), list(direc = "forward", I_subject = 4, J_subject = 8))
  expect_identical(give_coordinates(-1, "forward"), list(direc = "forward", I_subject = -1, J_subject = 0))
  expect_identical(give_coordinates(-1, "backward"), list(direc = "backward", I_subject = 1, J_subject = 0))
  expect_identical(give_coordinates(-1, "forward", J = 8, I = 5), list(direc = "forward", I_subject = 4, J_subject = 8))
  expect_identical(give_coordinates(-1, "forward", 4, 9), list(direc = "forward", I_subject = 3, J_subject = 9))
  expect_identical(give_coordinates(1, "forward"), list(direc = "forward", I_subject = 1, J_subject = 0))
  expect_identical(give_coordinates(1, "backward"), list(direc = "backward", I_subject = -1, J_subject = 0))
  expect_identical(give_coordinates(1, "forward", J = 8, I = 5), list(direc = "forward", I_subject = 6, J_subject = 8))
  expect_identical(give_coordinates(1, "forward", 4, 9), list(direc = "forward", I_subject = 5, J_subject = 9))
})
