test_that("give_coordinates() works as expected.", {
  expect_identical(give_coordinates(1, "forward"), list(direc = "forward", y_subject = 0, x_subject = 1))
  expect_identical(give_coordinates(1, "backward"), list(direc = "backward", y_subject = 0, x_subject = -1))
  expect_identical(give_coordinates(1, "forward", x = 8, y = 5), list(direc = "forward", y_subject = 5, x_subject = 9))
  expect_identical(give_coordinates(1, "forward", 4, 9), list(direc = "forward", y_subject = 4, x_subject = 10))
  expect_identical(give_coordinates(-1, "forward"), list(direc = "forward", y_subject = 0, x_subject = -1))
  expect_identical(give_coordinates(-1, "backward"), list(direc = "backward", y_subject = 0, x_subject = 1))
  expect_identical(give_coordinates(-1, "forward", x = 8, y = 5), list(direc = "forward", y_subject = 5, x_subject = 7))
  expect_identical(give_coordinates(-1, "forward", 4, 9), list(direc = "forward", y_subject = 4, x_subject = 8))
  expect_identical(give_coordinates(1i, "forward"), list(direc = "forward", y_subject = -1, x_subject = 0))
  expect_identical(give_coordinates(1i, "backward"), list(direc = "backward", y_subject = 1, x_subject = 0))
  expect_identical(give_coordinates(1i, "forward", x = 8, y = 5), list(direc = "forward", y_subject = 4, x_subject = 8))
  expect_identical(give_coordinates(1i, "forward", 4, 9), list(direc = "forward", y_subject = 3, x_subject = 9))
  expect_identical(give_coordinates(-1i, "forward"), list(direc = "forward", y_subject = 1, x_subject = 0))
  expect_identical(give_coordinates(-1i, "backward"), list(direc = "backward", y_subject = -1, x_subject = 0))
  expect_identical(give_coordinates(-1i, "forward", x = 8, y = 5), list(direc = "forward", y_subject = 6, x_subject = 8))
  expect_identical(give_coordinates(-1i, "forward", 4, 9), list(direc = "forward", y_subject = 5, x_subject = 9))
})
